### ISSUE TITLE
Sound Issue - Max Volume on Toggle

### ISSUE THREAD

**Issue by d-luisi** [robotswingset/narwhal-bugs#1]
When enabling sound on videos, it initially gets set to what sounds like max volume for a second or two before adjusting back to my iOS system volume level. My settings are to disable sound until I toggle it on, then have that setting remembered. This has been an issue before and after the recent update.

**Comment by rickharrison** [comment]
What iOS version are you currently on?

**Comment by d-luisi** [comment]
I’m currently on iOS 16.6.1 (20G81)

**Comment by rickharrison** [comment]
Closing, because I think Apple has fixed this with recent iOS versions
