### ISSUE TITLE
Cannot confirm login through app

### ISSUE THREAD

**Issue by aliofye** [robotswingset/narwhal-bugs#10]
**Describe the bug**
When logging into Reddit account, webview allows me to sign in, but when it's time to accept permissions for narwhal to access my accounts information nothing happens when I click on Accept

**To Reproduce**
1. Go to 'Settings->Accounts'
2. Click on 'Add new account'
3. Sign into Reddit account and try to click on Accept
4. Nothing happens

**Expected behavior**
I should be able to sign in

**Screenshots**
N/A

**Device Information:**
 - Device: iPhone15 Pro
 - OS: iOS 17.0.3

**Additional context**

**Comment by diyfixtool** [comment]
Maybe you can try the following methods

1. Force close the App. Then open the App and check if it works properly.

2. Restart your iPhone. Then open the app and check if it works properly

3. Delete the App. Please note that doing so may result in the loss of data stored in the App. Once completed, please re-download the App. Next, confirm whether the problem with the App has been fixed.

4. Contact a mobile phone repair professional. There may be a problem with the mobile phone. You can learn about PHONEFIX, a Chinese mobile phone repair company.

**Comment by rickharrison** [comment]
Reddit has informed me they fixed all sign in issues. If you are still having issues, please let me know
