### ISSUE TITLE
Annoying issues when editing long comments

### ISSUE THREAD

**Issue by coredumperror** [robotswingset/narwhal-bugs#11]
I've been dealing with mild annoyance in Narwhal for the longer comments I tend to write for years, but it usually didn't get too bad, and wasn't too frequent. Ever since 2.0, though, it's been frequently infuriating.

**Describe the bug**
There are two similar bugs that I'd like to get fixed:

Sometimes you completely lose the ability to scroll in the input form after you've written a lot of text. It'll move a bit when you drag, but then it'll pop right back to where it started. The location of the cursor seems to affect this, so randomly tapping around inside the form sometimes unlocks the scrollability. But I've occasionally just had to give up, post the comment, and then edit it to get the scrolling functionality back.

The second one's become extremely common since 2.0: trying to select text near the bottom of a long comment makes the entire form scroll up while you drag your finger to select text. This makes it completely impossible to select what you want, as the text is moving out from under your finger.

**To Reproduce**
The first one's hard to reproduce. It just pops up at random sometimes.

The second one seems highly reproducible. Just write/edit a longer comment (let's say 1500+ characters), then scroll to the bottom of the form. Double-tap to select a word, then attempt to drag the left or right side selector to anywhere else. The screen will scroll upwards even if you just leave your finger in place immediately after you start dragging.

**Expected behavior**
For the first one, I expect the form to scroll when I drag it around, and stay where I scrolled it to, instead of snapping back to the pre-drag position.

For the second, I expect the app to register a dragged text selector as a non-scrolling action, and only scroll the form if I attempt to drag the selector off the top or bottom of the textarea.

**Screenshots**
If I knew how to record my screen on iPhone, I could leave some videos of the second bug. But I haven't got a clue how to do that.

**Device Information:**
 - Device: iPhone 13
 - OS: iOS 16.6.1 (I just realized that 17 is available, yet it hasn't been suggested to me. I'm installing it now)
 - Narwhal Version: 2.102

**Comment by rickharrison** [comment]
This should be fixed in 2024.4 coming out later this week. Please let me know if you still experience after upgrading
