### ISSUE TITLE
PM window not displaying properly on iPad with Magic Keyboard 

### ISSUE THREAD

**Issue by OGAlphateam** [robotswingset/narwhal-bugs#14]
**Describe the bug**

I have an iPad that has a Magic Keyboard. 

When I was typing a PM to someone else I was in the message and I selected the empty text dialog box. My curser was in there just fine. As soon as I started to type it jumped below the screen. If I typed text it was there because I could see it when I removed the iPad from the keyboard. Then it rendered the on screen keyboard and it looked fine. Back in the keyboard and it repeated the issue. Outside it was fine. 

The first picture is before I start to type. 

The second one is after I type. You can see auto correct “sees” the text as it overlays the auto correct, but doesn’t show me the text I typed. 

![IMG_0070](https://github.com/robotswingset/narwhal-bugs/assets/147780627/90b1c660-d99d-45e5-b23e-aa7c3f7d1126)
![IMG_0071](https://github.com/robotswingset/narwhal-bugs/assets/147780627/37999748-576d-4a30-99b6-b12f9954f264)

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen. A link to the reddit post/page that you experienced this on is super helpful.

**Screenshots**

**Device Information:**
 - OS: [e.g. iOS8.1] iPad os 17.0.3
 - Version [e.g. 22] iPad Pro 

**Additional context**

**Comment by FarawayMagnet** [comment]
i have this issue as well, in Narwhal v2024.3 build 962, with an iPad Air 4 and Smart Folio Keyboard (or whatever it's called).

**Comment by rickharrison** [comment]
This is fixed in 2024.4 coming out laster this week!
