### ISSUE TITLE
Messages icon bug

### ISSUE THREAD

**Issue by TabFox-log** [robotswingset/narwhal-bugs#16]
**Description**
The Narwhal app is displaying the messages tab icon in red, whereas all the other icon are blue, as they are supposed to be.

**Steps to reproduce the behavior:**
1. Go to the app
2. Click on the menu
3. Find the messages tab

**Expected behavior**
The icon is supposed to follow the theme color, blue, and it is red.

**Device Information:**
 - Device: iPhone 12 mini
 - OS: iOS
 - Version 17

**Comment by rickharrison** [comment]
This has been fixed in the next version! (2.106)

Please re-open the issue if you are still experiencing it once the new app store build is out
