### ISSUE TITLE
Can't link my account after signing up.

### ISSUE THREAD

**Issue by ben-p-commits** [robotswingset/narwhal-bugs#19]
**Describe the bug**

**To Reproduce**
1. Go to link reddit account
2. Click on add new account
3. sign in via in-app browser
4. See error. looks like oauth req is busted.

![image](https://github.com/robotswingset/narwhal-bugs/assets/5067237/edb1ad06-9b27-47d2-9bf9-b608fabc921e)

**Expected behavior**
no error, account links.

**Device Information:**
 - Device: iphone 14 pro
 - OS: 17.0.3
 - Version app version is cut off in ui, cant read it.

**Additional context**
occurred right after subscribing to narwhal. was previously logged in with my reddit account too. got disconnected after signing up i guess

**Comment by rickharrison** [comment]
Are you still having an issue with this? Reddit may have been having issues that day with their API
