### ISSUE TITLE
Constantly returns “ no posts found” when searching

### ISSUE THREAD

**Issue by Tropicalheat03** [robotswingset/narwhal-bugs#24]
**Describe the bug**
Whenever searching anything there is always no results found
**To Reproduce**
1. Go to 'search'
2. Search “ houses”
3. Click on 'search all posts for houses'

**Expected behavior**
The search results for houses 

**Screenshots**

![IMG_0918](https://github.com/robotswingset/narwhal-bugs/assets/153141381/a8871d8a-4be7-4094-bf87-f204385ae148)

**Device Information:**
 - Device: [e.g. iPhone14pro]
 - OS: [e.g. iOS17.1.2]
 

**Additional context**

**Comment by rickharrison** [comment]
Is this still happening for you? Reddit may have been having issues that day
