### ISSUE TITLE
Subscription auto-renewal not automatically detected

### ISSUE THREAD

**Issue by fspmarshall** [robotswingset/narwhal-bugs#25]
**Describe the bug**

The next time I opened the app after my subscription auto-renewed I was taken back to the initial prompt asking me to subscribe as if I didn't have a subscription. Clicking 'restore purchases' works, but the UX is rough.

**To Reproduce**

Unsure since this was the first time renewal.  Might be a rare edge-case, or it might happen every time.

**Expected behavior**

Automatic renewal should be seamless.

**Comment by rickharrison** [comment]
Did you cancel your subscription first and then re-subscribe? I haven't heard of this happening before. Please let me know if it happens again.
