### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by gh0sti** [robotswingset/narwhal-bugs#26]
**Describe the bug**
API issue

**To Reproduce**
1. Load app, nothing loads, can't sign in after signing out. 

**Expected behavior**
App should load reddit posts
App should allow user to sign into Reddit account to pull user data
**Screenshots**

![image](https://github.com/robotswingset/narwhal-bugs/assets/4202657/b9d71b5f-cc20-44ff-94ff-e154c1ec0d85)

![image](https://github.com/robotswingset/narwhal-bugs/assets/4202657/a15a01f8-cc6a-4fe3-b090-fc867885cbf6)

**Device Information:**
 - Device: [iPhone 15 Pro Max]
 - OS: [17.2]
 - Version [2.110]

**Additional context**
Possible API issue with narwhal

**Comment by rickharrison** [comment]
I think Reddit was having issues that day. Please post again if you are still having an issue.
