### ISSUE TITLE
Bug Report - Unable to Login to Reddit Account on Narwhal2 App

### ISSUE THREAD

**Issue by Teknevra** [robotswingset/narwhal-bugs#27]
**Describe the bug**

I am experiencing an issue with the Narwhal2 App where I am unable to log in to my Reddit Account. Although I can access the Narwhal2 App without any problems, attempting to log in to my Reddit Account results in an Error Message.

**To Reproduce**

	1.	Open Narwhal2 App.
	2.	Navigate to the login section.
	3.	Enter Reddit Account credentials.
	4.	Attempt to log in.

**Expected behavior**
Successful login to the Reddit Account within the Narwhal2 App.

**Screenshots**
N/A

**Device Information:**
	•	Device: IPhone 11 
	•	Operating System:IOS 17.2.1
	•	Narwhal2 App Version: v2.113, build 949

**Additional context**
Please investigate and resolve this login issue promptly. If further information is required, feel free to contact me.

**Comment by rickharrison** [comment]
@Teknevra Are you still having this issue?

**Comment by rickharrison** [comment]
Reddit has informed me they fixed all sign in issues. If you are still having issues, please let me know
