### ISSUE TITLE
Multireddits

### ISSUE THREAD

**Issue by TigerxTyger** [robotswingset/narwhal-bugs#35]
**Describe the bug**
created multireddits no longer showing, sidebar tab just displays "loading..."

**To Reproduce**
1. Go to 'sidebar'
2. Click on 'multireddits'
3. See error "Loading..."

**Expected behavior**
Expected to see previously created multireddits

**Screenshots**
![IMG_9165](https://github.com/robotswingset/narwhal-bugs/assets/154981171/a9704135-f98f-49d3-bbfa-fa34a7a24351)

**Device Information:**
 - Device: iPhone 13Pro
 - OS: iOS 17.4.1
 - Version 17.4.1

**Additional context**
None

**Comment by rickharrison** [comment]
Is this still happening for you?

**Comment by TigerxTyger** [comment]
Occasionally but it doesn’t last as long as previously. Usually fixes after i force quit the app and restart. On Jun 15, 2024, at 8:36 PM, Rick Harrison ***@***.***> wrote:﻿
Is this still happening for you?
