### ISSUE TITLE
Searching inside a filtered subreddit returns no results

### ISSUE THREAD

**Issue by Tumleren** [robotswingset/narwhal-bugs#39]
**Describe the bug**
When browsing a filtered subreddit and attempting to search inside that subreddit, no search results are shown

**To Reproduce**
1. Filter a subreddit 
2. Visit the subreddit and perform a search 
3. No search results are shown

**Expected behavior**
For search results to be shown regardless of whether the subreddit is filtered, but only when searching inside the subreddit. A search outside the subreddit should not display results from the subreddit when the subreddit is filtered

**Screenshots**
https://imgur.com/a/DlUHVvb

**Device Information:**
 - Device: iPhone 12
 - OS: iOS 17.5.1
 - Version: 2024.5

**Additional context**
The case of filtering a subreddit you still visit is helpful in avoiding spoilers e.g. for sports and TV-shows and I feel searching inside a filtered subreddit should be supported

**Comment by rickharrison** [comment]
This has been fixed in 2024.8. Please let me know if you are still experiencing this issue
