### ISSUE TITLE
Swiping out of search causes visual issues with keyboard

### ISSUE THREAD

**Issue by bndbg** [robotswingset/narwhal-bugs#4]
When on the search page, having swipe to go back as a gesture causes the keyboard to detach from the bottom of the screen.

1. Have "Swipe anywhere to go back" on
2. Open the search page
3. Swipe right to go back
4. See the issue

**Expected behavior**
The keyboard should slide out of the way as the search page is dragged off screen.

https://github.com/robotswingset/narwhal-bugs/assets/79026759/928f9fcc-5e04-4a4c-94d6-72f1c400596e

**Device Information:**
 - Device: iPhone 15 Pro Max
 - OS: iOS 17.0.2

**Comment by bndbg** [comment]
Appears to be fixed in latest update (2.102), Thanks Dev!

**Comment by rickharrison** [comment]
Thanks for reporting!
