### ISSUE TITLE
Poor UX when navigating between items in action bar

### ISSUE THREAD

**Issue by kylepeeler** [robotswingset/narwhal-bugs#43]
**Describe the bug**
Some of the SFIcons used in the nav bar are using .fill, while others are not. I suggest only applying .fill when the user has selected the icon, as it makes it seem to the user a screen is selected compared to the others, or just remove .fill entirely from the All option (use square.stack.3d.up, not square.stack.3d.up.fill)

Currently there is no color differentiation when a user selects the tab. Compare behavior to other native iOS apps like Music, Phone, etc... they all change the color when the user selects a screen. 

The combination of the two is confusing UX for me at times.

**To Reproduce**
1. Go to settings
2. Click on action bar & navigation editor
3. Include View All in your action bar (my setup is Home, View All, View Popular, View Saved, Menu)
4. Compare the different icons, see which one sticks out at you.

**Expected behavior**
View all should blend in with the other icons visually, and should have some color differentiation when the screen is currently selected/shown on screen.

**Screenshots**
![IMG_0992](https://github.com/user-attachments/assets/794d7f0d-37a7-4eae-8b09-cee76d3c6b2c)

**Device Information:**
 - Device: iPhone 15 Pro
 - OS: iOS 18

**Additional context**

**Comment by rickharrison** [comment]
This will be fixed in 2024.9
