### ISSUE TITLE
Random NSFW Not Loading a Subreddit

### ISSUE THREAD

**Issue by thrasherjake** [robotswingset/narwhal-bugs#54]
When clicking the ‘Random NSFW Subreddit’ button the screen will change and perpetually show a loading circle. The subreddit never loads. 

**To Reproduce**
1. Open Side Menu
2. Press ‘Random NSFW Subreddit’
3. Error Occurs

**Device Information:**
 - Device: iPhone 14
 - OS: iOS 18.1.1
 - Version 2024.10

**Comment by hambone43** [comment]
Came here to report this as well. Additionally, “Random” (without NSFW) is also no longer functioning properly.

**Comment by ranovr** [comment]
Same. Random and Random NSFW both are not working

**Comment by rickharrison** [comment]
This will be fixed in 2024.11! Coming out in the next few days
