### ISSUE TITLE
Switching to full screen pauses videos

### ISSUE THREAD

**Issue by Endemoniada** [robotswingset/narwhal-bugs#6]
**Describe the bug**
When tapping the button to take a video full screen, it does so but then immediately pauses the video as well. This is 100% repeatable. 

**To Reproduce**
open a video in media view
Tap anywhere to bring up the controls
Press full-screen
The video will full screen, then pause. 

**Expected behavior**
Video should simply switch to full screen and keep playing.
Additionally, it would be nice if the controls showed for a second after opening, to allow immediate full screen. Or, allowing double-tap to enter full screen. 

**Device Information:**
 - Device: iPhone 12, iPhone 15
 - OS: iOS 17
 - Version: 2.101

**Comment by rickharrison** [comment]
This is fixed in the next app store version which should be out in the next few days. Please let me know if you are still experiencing this then
