### ISSUE TITLE
Permanent notification badge

### ISSUE THREAD

**Issue by NoizeTank** [robotswingset/narwhal-bugs#9]
I have a notification badge that will not go away nor will it change number, regardless of how many new messages or replies I have. 

![IMG_7108](https://github.com/robotswingset/narwhal-bugs/assets/46335765/d1715a74-f24e-4ff8-b2bb-591f1f89ef03)

**Comment by rickharrison** [comment]
This is probably from Narwhal 1, I will try and fix this in the new update

**Comment by rickharrison** [comment]
This should be fixed! Please let me know if you are still experiencing this
